spring:
  h2:
    console:
      enabled: true
      path: /h2-console

#  datasource:
#    username: sa
#    password:
#    url: jdbc:h2:mem:appdb
#    #     jdbc:h2:file:~/data/appdb
  profiles:
    active: dev